# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Feedback', models.TextField(max_length=50)),
                ('Food_Quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('dissatisfied', 'Dissatisfied')], max_length=12)),
                ('Location_Visited', models.CharField(choices=[('Location1', 'Location1'), ('Location2', 'Location2'), ('Location3', 'Location3')], max_length=9)),
            ],
        ),
    ]
