# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingAirTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Travel_From_Date', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 9, 9, 4, 225312))),
                ('Travel_To_Date', models.DateTimeField(default=datetime.datetime(2019, 2, 27, 9, 9, 4, 225349))),
                ('Travel_From', models.CharField(max_length=50)),
                ('Travel_To', models.CharField(max_length=50)),
                ('No_of_person', models.IntegerField()),
            ],
        ),
    ]
