# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookingairticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingairticket',
            name='Travel_From_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 10, 2, 45, 248624)),
        ),
        migrations.AlterField(
            model_name='bookingairticket',
            name='Travel_To_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 10, 2, 45, 248660)),
        ),
    ]
