# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190227_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoreis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingairticket',
            name='Travel_From_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 12, 5, 3, 402564)),
        ),
        migrations.AlterField(
            model_name='bookingairticket',
            name='Travel_To_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 12, 5, 3, 402601)),
        ),
    ]
