# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190228_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='name',
            new_name='Name',
        ),
    ]
