# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190228_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_review',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Hello'),
        ),
    ]
