# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('country', models.CharField(choices=[('india', 'India'), ('us', 'US'), ('canada', 'Canada'), ('australia', 'Australia'), ('spain', 'Spain'), ('japan', 'Japan')], max_length=10)),
            ],
        ),
    ]
