# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-05 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('username', 'email')]),
        ),
    ]
