# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-05 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20190305_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
