# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
