# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20190221_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Address',
            field=models.TextField(max_length=50),
        ),
    ]
