# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20190222_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
        migrations.AlterField(
            model_name='author',
            name='lat_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
