# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20190222_0500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together=set([('Name', 'Address')]),
        ),
    ]
