# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-18 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
