# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_auto_20190306_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
