# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0004_auto_20190307_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
