# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-08 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0005_auto_20190307_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('description', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=100)),
                ('picture', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
