# Generated by Django 2.1.2 on 2019-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0006_shopping_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopping_Cart',
        ),
    ]
