# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-11 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0008_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name=b'client_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name=b'brand',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name=b'description',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name=b'summary',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name=b'type',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name=b'weight',
        ),
    ]
