# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-11 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0010_auto_20190311_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
