# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0014_auto_20190311_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.CharField(default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
