# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0015_auto_20190313_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('c', 'Confirm'), ('d', 'Draft')], default='d', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
