# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileUser', '0002_auto_20190228_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
