# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-04 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('ProfileUser', '0003_auto_20190301_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
